### ISSUE TITLE
Sample Patients

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#110]
Can you please provide test patients that have data for appointments, medications and coverages.  We've tried the test patient provided in the documentation and are not able to pull back data.

**Comment by Torin-Shepard-athena** [comment]
CPS Practice Management resources allow searching across patients, bug Clinical resources do not (this is by design to avoid HIPAA concerns/risks).

Coverage resource can be searched across patients without any search parameters.  Use _count parameter to request more than the default size of 20 resources in the response Bundle
Coverage?_count=50

Appointment without any search parameters will return OperationOutcome indicating Appointment resource requires location parameter to be able to search across patients.  The location ids can be discovered by querying Location resource.

Location resource can be searched across patients without any search parameters.
Location?_count=50

Extract location ids with prefix “FAC-“ for facilities.

Query Appointment by a list of facilities
Appointment?location=FAC-403,FAC-404,FAC-405,FAC-406

**Comment by jdmaple** [comment]
@Torin-Shepard-athena  - we've tried this approach and so far we've had limited success in finding a patient with medications.  Do you have a handful of PatientIds you can recommend for testing?

**Comment by jdmaple** [comment]
Thank Torin - we were able to find patients with medications.
