### ISSUE TITLE
Sandbox Data

### ISSUE THREAD

**Issue by jdmaple** [virencehealth/apiserver.virencehealth.com#114]
Is there a way to see what data is in the sandbox? How do we get a full patient or resource list?

**Comment by Torin-Shepard-athena** [comment]
The sample work account provider (Practitioner) listed on [API Access](https://mydata.athenahealth.com/access-centricity-apis) is authorized to perform multiple FHIR queries with and without various search parameters to discover the data.  This may require some learning and creativity.

CPS FHIR API Server allow searching for resources across patients for Practice Management resources but not for Clinical resources (this is by design to avoid HIPAA concerns/risks).

It is possible to get a Bundle of all System resources of a given type without search parameters (e.g. Location, Organization, Practitioner).

[Issue #118](https://github.com/virencehealth/apiserver.virencehealth.com/issues/118) has a comment that explains how the :missing modifier can be used to get a list of Patient resources in CPS API Sandbox.

**Comment by jdmaple** [comment]
@Torin-Shepard-athena - this was very helpful, thank you!! We are able to retrieve patients using the methods you described.

**Comment by Deiva1** [comment]
I have completed as per api access,(https://ap22sandbox.fhirapi.athenahealth.com/demoAPIServer/oauth2/authorize?state=defaultState&
scope=openid%20profile%20patient/*.read%20launch/patient&
response_type=code&redirecturi-'my_redirecturl').
If I am passing the patient id to get the patient details and the response an getting is error,
kindly share me some API information to insert records and fetch all patient details 
![image](https://github.com/athenahealth/api
