### ISSUE TITLE
Search appointments by different actors doesn't work

### ISSUE THREAD

**Issue by royyin224** [virencehealth/apiserver.virencehealth.com#133]
**Describe the bug**
When trying to search appointments by different actors, like location, practitioner role or device, the api doesn't recognize the search request

**To Reproduce**
Send a GET request to 

```[api root]/fhir/Appointment?_count=100&_format=json&_summary=data&actor=Location/FAC-3```

**Expected behavior**
It should return all appointments that have participant 'Location/FAC-3', as described in the standard:

- [Appointment search](https://www.hl7.org/fhir/appointment.html#search)
- [Reference type](https://www.hl7.org/fhir/search.html#reference)

**Response from API**
```
{
    "resourceType": "OperationOutcome",
    "text": {
        "status": "generated",
        "div": "<div xmlns=\"http://www.w3.org/1999/xhtml\"><table width=\"100%\"><tbody><tr><td width=\"25%\"><span class=\"text-muted\">Outcome null</span></td><td width=\"42%\"><span class=\"text-muted\"><table><thead><tr><th>#</th><th>Severity</th><th>Type</th><th>Detail</th></tr></thead><tbody><tr><td>1</td><td>ERROR</td><td>BUSINESSRULE</td><td>Reference Location/FAC-3 does not match ^-?0$|^-?[1-9][0-9]*$ in query parmeter</td></tr></tbody></table></span></td></tr></tbody></table></div>"
    },
    "issue": [
        {
            "severity": "error",
            "code": "business-rule",
            "diagnostics": "Reference Location/FAC-3 does not match ^-?0$|^-?[1-9][0-9]*$ in query parmeter"
        }
    ]
}
```

**Additional note**
The given example can be overcome by changing the search request to 

```[api root]/fhir/Appointment?_count=100&_format=json&_summary=data&location=FAC-3```

but we still need to search for other type of actors, like devices, since we still can't find any test appointment in the API sandbox that has any device related to it, we are using location for test.

If you can provide us any test appointment that have devices or nurses as participants, that will greatly help our development.

**Comment by Amits2070** [comment]
Hi,
Currently Appointment resource supports searching actor by reference to Patient, Practitioner, or Location participating in the appointment. Other resource types are not supported.

The business rule error (like **### "code": "business-rule" "diagnostics": "Reference Location/FAC-3 does not match ^-?0$|^-?[1-9][0-9]*$ in query parmeter"** ) for searching actor by reference to Location is a known issue that will be fixed in a future release.

The API Sandbox has appointments for the following Practitioners.
1588761792000020
1588761792000060
1588761792000070
1588761792000080
1588761792000090
1588761792000100

Example:
[api root]/fhir/Appointment?_count=100&_format=json&_summary=data&actor=Practitioner/1588761792000020

**Comment by royyin224** [comment]
Thanks for your reply, do you have plans to support other resource types in the future?

**Comment by Amits2070** [comment]
Hi ,
Our core product doesn't support searching appointments with any devices attached to it.
In future we cant provide support for this type of resources.

**Comment by royyin224** [comment]
Thank you, we hope to see this feature soon
