### ISSUE TITLE
Production client/secret

### ISSUE THREAD

**Issue by sr5732358** [virencehealth/apiserver.virencehealth.com#134]
**Your question**

We have a test connection using client/secret in https://mydata.athenahealth.com/my-apps for sandbox testing.  We have a new customer and need production client/secret.  Do we create those in https://mydata.athenahealth.com/my-apps too?

**Comment by Amits2070** [comment]
Yes. Production applications should be registered on the same developer portal.  This required when different redirect URLs are used in staging/test than are used in production.  Creating a new application is required in order to use different redirect URLs because the redirect URLs are associated with each client id.
