### ISSUE TITLE
Obtaining CDA

### ISSUE THREAD

**Issue by soneal-relatient** [virencehealth/apiserver.virencehealth.com#145]
Is it possible to pull a full CDA document for a patient without needing to know who created the file (author)?

We are having troubles lining up the values returned from the individual CDA-like endpoints (Procedure, Immunization, etc.) with what would be sent in a CDA document when a patient updates their information.

**Comment by soneal-relatient** [comment]
Is it possible to get any information on this?

**Comment by craaby** [comment]
It will be helpful if you can provide more details about what kind of CDA you are trying to pull and steps you are following.

Based on FHIR endpoints you have mentioned like (Procedure, Immunization etc. ) we are assuming that you are trying to generate 2.1 CDA document which is one of CVS(ClinicalVisitSummary, VDT(AmbulatorySummary), TOC(Transition of Care) etc.
supported by the system.

If you are trying to pull CDA using UI, it supports only 2 types of CDA documents – ClinicalVisitSummary and Transition Of Care. These documents uses different FHIR queries along with filters (search parameters ) to pull out data which will be included in CDA document. It is possible that because of filter criteria used in FHIR queries its not pulling all the records in specific type of CDA document. Example, ClinicalVistiSummary mostly pulls active clinical items. You can find these FHIR queries in "docmap" directory under "cda-generator-master" project under JBOSS.

**/DocumentReference** API exposes **$generate** operation which can be used to query different type of CDA documents, one of which is VDT (AmbulatorySummary) which helps to pull all the data including historical data.

Typical call for this API will look like – fhir/DocumentReference/$generate?raw=true&patient=Patient/{PID}&author=Practitioner/{PVID}&class=AmbulatorySummary&type=34133-9&format=urn:hl7ii:2.16.840.1.113883.10.20.22.1.2:2015-08-01

You can pull Patient resource using “/Patient” endpoint and use Patient.id as {PID} and practitioner reference as {PVID} in above FHIR query or use any other practitioner from the system. But author is required to pull CDA for patient using $generate operation. Similarly, $generate operation allows to create different types of 2.1 CDA documents.

**Comment by soneal-relatient** [comment]
@AbhijeetB619 Thanks for the response.

We have been trying to setup a system that pulls patient's clinical information through the API, shows a subset of that data for the patient to update and then we send the updated data back through the API.

We've been trying to line up the value from the individual endpoints with what's necessary in a valid CDA 2.1 document and there's been many disconnects in terms of the values and properties.

**Comment by venkatakreddyc** [comment]
@soneal-relatient, 
We've been trying to line up the value from the individual endpoints with what's necessary in a valid CDA 2.1 document and there's been many disconnects in terms of the values and properties? 
Not clear what are the disconnects which you observed and also not clear on what are you trying to setup? could you please be more precise here.
