### ISSUE TITLE
Signon reprompt from Access My Data url

### ISSUE THREAD

**Issue by sr5732358** [virencehealth/apiserver.virencehealth.com#148]
**Your question**

Using the Access My Data url for a work account (i.e. {fhirserverurl:port}/{cps/cemrdbname}APIServer/oauth2/authorize?)... I'm always prompted to enter user credentials for hwinston@sboxprovtenant.com .  I always get a 'Stay Signed In' screen.  If I click yes, and then rerun the 'Access My Data' url.... I still have to signin the next time I run the Access My Data url.  My expectation is that I would not have to re-enter my credentials again once I select 'Stay Signed In'

Why does this behavior exist? Is it an Active Directory setting?  I am working with a customer and would like to be able to instruct them how to bypass having the signon screen come up with each and every sso request.
<img width="1440" alt="Screen Shot 2020-07-21 at 5 54 57 PM" src="https://user-images.githubusercontent.com/24782324/88118999-65a64480-cb7c-11ea-9f64-d12ef52c57ea.png">

**Comment by AjeetYadav07** [comment]
No, It is not  Active Directory setting. A connection to any internet website has a timeout built-in.... usually 30 minutes...
The internet works by sending 'requests' to a web server, which in turn sends a response back to the web browser....
If your web browser does not send any requests to the server in the 30 minute timeout period, the server will end the session (viz: log you out). When you return to use your computer after the session timeout period, any subsequent requests from your browser will attempt to create a new server session and log you back in.....
To avoid having to log-in to a public website each time you wake your computer or use a tab that you have left open for some time
Select the option on the login screen to "Keep me logged in" or "Remember me" on the site login screen.
This will not stop a web server you are connected to from timing out, but it will enable the server to log you back in automatically when you make a request after the timeout period.
Can u please look at the below link :
https://answers.microsoft.com/en-us/ie/forum/all/staying-logged-in-to-microsoft-account/811d541d-0f5c-466a-95bf-43068c7925fc#:~:text=Press%20Ctrl%20%2B%20Shift%20%2B%20Delete%20%3E,in%20your%20Microsoft%20account%20automatically.

**Comment by sr5732358** [comment]
Regarding the "Keep me logged in" or "Remember me"... I was trying to explain that I DO indeed select this option when I signin with hwinston@sboxprovtenant.com in the sandbox environment. If I turn around and send a new request (after only 1-2 minutes), it does not ' enable the server to log me back in automatically '.  I always get the login screen.  Is that broken?  I can reproduce the issue at will.

**Comment by AjeetYadav07** [comment]
We can disable the "remain signed in"  by configuring KMSI and also can configure authentication session management with Conditional Access. Follow the given link below : 
1. https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/keep-me-signed-in#:~:text=Select%20Azure%20Active%20Directory%2C%20select,until%20they%20explicitly%20sign%20ou
2. https://docs.microsoft.com/en-us/azure/active-directory/conditional-access/howto-conditional-access-session-lifetime
We would not be able to disable this option or create a new policy on the public sandbox that is provided here due to certain organizational policies.
Can you please work with the customer if they would like to disable the same in customer AAD?
