### ISSUE TITLE
Sandbox Server URL are not accessible

### ISSUE THREAD

**Issue by saravanakumargs** [virencehealth/apiserver.virencehealth.com#166]
Hi,

I am not able to access the demoapi server url

https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/metadata

Getting error as 502 - Web server received an invalid response while acting as a gateway or proxy server.

I tried in the different browser and different device. Still getting the same error.

Can you please let me know if the the URL is correct.

Thanks,
![502](https://user-images.githubusercontent.com/77644386/104965156-b8ce4800-59a3-11eb-825f-da65f526db97.png)

**Comment by AjeetYadav07** [comment]
URL is correct. Please try, it is working fine. 
![image](https://user-images.githubusercontent.com/68940876/104992131-5d08cb00-5a46-11eb-9415-f0e646f3321a.png)

**Comment by saravanakumargs** [comment]
Now I am able to get the metadata url

**Comment by dwwinters** [comment]
I am also currently running into this issue.  I'm guessing the sandbox is down?

**Comment by Torin-Shepard-athena** [comment]
As noted on the readme the main page of this GitHub forum, we are in the process of changing the DNS name to transition from Virence to athena.
 
As part of this change, we will be reconfiguring the system to accept requests on default https port 443 instead of port 9443.
 
The 9443 port number has been removed from the URLs.
 
https://cpsapisandbox.virenceaz.com/demoAPIServer/fhir/metadata
https://cpsapisandbox.virenceaz.com/demoAPIServer/oauth2/authorize
https://cpsapisandbox.virenceaz.com/demoAPIServer/oauth2/token
 
When the change is complete, you will use cpsapisandbox.fhirapi.athenahealth.com instead of cpsapisandbox.virenceaz.com
