### ISSUE TITLE
Novo 2.0 project - CHC//Novo - RelatedPerson Search by name

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#52]
Does the RelatedPerson search (GET) truly require the ID of the patient?

Shouldn't I be able to chain a search together like the following knowing that the patient is a "reference":
https://saturn.mychc1.com:9443/practicemanagertstAPIServer/fhir/RelatedPerson?_format=json&_summary=data&_count=1000&patient:Patient.name=test

**Response:**
 "issue": [
        {
            "severity": "error",
            "code": "business-rule",
            "diagnostics": "Reference test does not match ^-?0$|^-?[1-9][0-9]*$ in query parmeter"
        }
    ]

Interestingly - if I change the value I'm searching over to numeric, I don't get an error, but do get 0 responses:
https://saturn.mychc1.com:9443/practicemanagertstAPIServer/fhir/RelatedPerson?_format=json&_summary=data&_count=1000&patient:Patient.name=1
Response:
 "type": "searchset",
    "total": 0,
    "link": [
        {
            "relation": "self",
            "url": "https://saturn.mychc1.com:9443/practicemanagertstAPIServer/fhir/RelatedPerson?_count=1000&_format=json&_summary=data&patient%3APatient.name=1"
        }
    ]

**Comment by SameerSingh1991** [comment]
Yes the RelatedPerson requires the reference of the Patient. 

Please refer search parameters of RelatedPerson resource from the link https://smartappdocsprod.azureedge.net/relatedperson.html#search. 
Here you can see that for search based on Patient you need to provide a reference. 
The definition of reference in this case is a Patient ID or a Patient URL . Please refer following URL for definition of reference in this case.
https://smartappdocsprod.azureedge.net/relatedperson.html#search

So you cannot use patient name to search for a RelatedPerson resource but when you replace the name with a number FHIR server takes it as the patient ID and since it is not able to find any patients with that ID it returns 0 rows.

**Comment by Torin-Shepard-athena** [comment]
RelatedPerson patient search parameter value must be valid id from a Patient resource.
Example: RelatedPerson?patient=123456789101230 would find RelatedPerson resources for the Patient resource where Patient.id=123456789101230
