### ISSUE TITLE
Missing Medication resources 

### ISSUE THREAD

**Issue by michelemottini** [virencehealth/apiserver.virencehealth.com#59]
EG https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/MedicationOrder/1239657704150620 contains:

```
        "medicationReference": {
          "reference": "Medication/13470",
          "display": "MEVACOR TAB 40MG"
        },
```

but attempts to GET https://cpsapisandbox.virenceaz.com:9443/demoAPIServer/fhir/Medication/13470 fail with a 404 status code

**Comment by Torin-Shepard-athena** [comment]
Medications sometimes change over time.  Drugs which may have been prescribed in the past may no longer be available to be prescribed today.  When the medication reference list is updated, it is expected behavior that some obsolete drugs are removed from the list and references to old medications may become orphaned.
Centricity client application is able to detect charts with obsolete medications and display messages and prompt clinicians to select new, active medications.  Unfortunately, this use case is more complex for the API which can only indicate when references are no longer valid by returning zero Medication resources for obsolete drugs.

**Comment by michelemottini** [comment]
I see.
So the MedicationOrder with the orphaned reference should be considered invalid and ignored?

**Comment by Torin-Shepard-athena** [comment]
Even if MedicationOrder.medicationReference.reference has orphaned reference to Medication which no longer exists, the MedicationOrder resource is still valid as a prescription for the corresponding MedicationStatement.

MedicationOrder.medicationReference.display still gives the text description of the drug that was prescribed.

**Comment by michelemottini** [comment]
The [FHIR specs](http://hl7.org/fhir/DSTU2/references.html) are pretty clear that references should resolve: 'Whether or not the reference is to a FHIR RESTful server, the reference SHALL point to a Resource as defined by this specification'. A resource with references that do not resolve is definitely not valid
