### ISSUE TITLE
Novo 2.0 project - CHC//Novo - Patient.Facility available over the API?

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#60]
I'm working with CHC on an integration, and there is great interest in getting the "Facility" field (found in the patient's demographics screen) in the downstream application, as well as being able to update within GE.

![image](https://user-images.githubusercontent.com/20426558/66596842-a09a3700-eb6b-11e9-92fd-53556b44a68a.png)

I'm not finding anything in the documentation, nor coming back in the /Patient calls that we're making.

Curious if I'm just missing it somewhere, or if there's another call it's under.
Beyond that - wondering if it's something that can be configured to be available over the /Patient endpoint.

Thanks -

**Comment by Torin-Shepard-athena** [comment]
Facility is not output in CPS FHIR Patient resources. This is by design because FHIR Patient resource does not have any element that references a Location, and CPS Facilities are mapped in the Location Resource using "FAC-" prefix.

We could consider implementing a non-standard extension to the CPS FHIR Patient as an enhancement which could possibly benefit other customers.  Product management would need to to decide if this would be prioritized for inclusion in a future release.

**Comment by Torin-Shepard-athena** [comment]
Enhancement request put into the system for future release.
