### ISSUE TITLE
/Coverage Endpoint - additional fields inquery (CHC//Novo install)

### ISSUE THREAD

**Issue by andylebo** [virencehealth/apiserver.virencehealth.com#66]
Hello - 
Working with CHC on bi-directional Coverage updates.
Is there any way to get the "Patient Relationship to Insured:" field to come out over an API call? I'm not seeing that it is at this point.  Additionally, the demographics of this insured if it really is of a type of "Other" would be great as well.

**There are other fields such as "Group Name" that don't seem to be available either - and would be great.

![image](https://user-images.githubusercontent.com/20426558/67494240-874ebb80-f63e-11e9-99f4-f9181ac26e16.png)

**Comment by Torin-Shepard-athena** [comment]
Patient relationship to insured element was _not_ available in FHIR DSTU2.  It was added in FHIR STU3.

We need to consider multiple FHIR versions and the optimal solution before we decide if/how Centricity API Server should support mapping additional fields to FHIR elements.  We also must consider differences in data models between CPS and C-EMR because the single API Server supports both product types.

Here are relevant facts about Coverage resource type and group name.

Some time is needed to decide the best enhancements that could be made to Coverage resource.

Some elements in CPS/C-EMR do not map to FHIR and would require FHIR extensions.

Insurance "groups" in Coverage resource is a good example of how FHIR data model has changed over time.
 
https://smartappdocsprod.azureedge.net/coverage.html
http://hl7.org/fhir/DSTU2/coverage.html

[FHIR Changes from DSTU2 to STU3](http://hl7.org/fhir/STU3/diff.html)
Coverage.relationship - Added Element
Coverage.grouping - Added Element
Coverage.group - Deleted

[FHIR Changes from STU3 to R4](http://hl7.org/fhir/diff.html)
Coverage.grouping - Deleted Element

**Comment by Rinkal-jain** [comment]
This functionality is not currently supported and may be considered for a future release but is not yet planned.
