### ISSUE TITLE
CPS 19 - FHIR - Patient.Read

### ISSUE THREAD

**Issue by sangkars** [virencehealth/apiserver.virencehealth.com#83]
Is it possible to get patient language through FHIR ?

Kind Regards,
Sangkar

**Comment by saikumarreddy1994** [comment]
Any Updates ?

**Comment by mikeseale** [comment]
Just wanted to confirm that language shows in v19's FHIR API when calling the patient resource, but it does NOT show for Centricity 12.3:


**[base]/fhir/Patient/{id}**

![image](https://user-images.githubusercontent.com/11613689/68954924-9252c280-078a-11ea-8a0c-75c614a807aa.png)

**Comment by Torin-Shepard-athena** [comment]
Patient Language will be mapped in Centricity FHIR Patient API in both 12.3 and v19.

Patient language is optional in CPS.  If the patient does not have any language set in CPS Registration module, then communication.language element will be absent from CPS FHIR Patient resource.  Some patients in the CPS API Sandbox do not have language.

Patient?language:missing=false query will show a list of patients that have preferred language.

**Comment by mikeseale** [comment]
I think I found the issue with my CPS12.3 example.  Not all language values are go over the FHIR interface.  Possibly due to being unmapped?  The interface will not send an unknown value in this case, but it will act like there is nothing filled out in the patient's registration.

Registration selection:

![image](https://user-images.githubusercontent.com/11613689/68973474-fdfd5580-07b3-11ea-83a6-7a2151d44c89.png)


Missing between marital status and care provider:

![image](https://user-images.githubusercontent.com/11613689/68973423-de662d00-07b3-11ea-8470-62f9a48c7781.png)


It does work when I update this to Chinese or English.
