### ISSUE TITLE
Managing Access Controls for FHIR

### ISSUE THREAD

**Issue by shivBshah** [virencehealth/apiserver.virencehealth.com#99]
How would you manage access controls ( permissions ) to FHIR resources for a service user in CPS or EMR ? 
I would think my permissions from CPS would transfer to FHIR resources. For example: if I can create appointments in CPS, I should be able to do so using fhir too, but that doesn't seem to be the case.

Any help is highly appreciated.

**Comment by KedarGanta** [comment]
@shivBshah  You can manage permissions for the users of your app in Centricity.

In Centricity, under Admin > Users >  User Management > Open User account > Select Security tab >  Select 'API Server User' group >Under Permission List, select the appropriate access.

**Comment by shivBshah** [comment]
@KedarGanta  Tried following  the steps you mentioned, and currently have this in Centricity.

![image](https://user-images.githubusercontent.com/16928011/73194227-799f4b00-40f1-11ea-99a4-071e191994f5.png)

As you can seen, I have the permission to add/update/delete observations, but I don't see the observation.write scope getting returned back with the token response; I am asking for all the read/write scopes (user/*.*) in my authorization request.

These are the permissions I am granted after authorization: 

``` scope: "user/MedicationStatement.read user/RelatedPerson.read user/Location.read user/ValueSet.read user/DocumentReference.write user/MedicationAdministration.read user/BasicAdvanceDirective.read user/MedicationOrder.read user/Medication.read user/Condition.read user/Patient.write openid profile user/Goal.read user/Organization.read user/RelatedPerson.write user/Procedure.read user/Observation.read user/Appointment.read user/CarePlan.read user/Device.read user/BasicPosting.read user/Binary.read user/AuditEvent.read user/Patient.read user/ConceptMap.read user/Practitioner.read user/Schedule.read user/Coverage.write user/Appointment.write user/Encounter.write user/Immunization.read user/ProcedureRequest.read user/NamingSystem.read user/Coverage.read offline_access user/ReferralRequest.read user/DocumentReference.read user/Encounter.read user/BasicAccount.read user/AllergyIntolerance.read user/OperationDefinition.read user/DiagnosticOrder.read user/BasicPosting.write user/Binary.write user/FamilyMemberHistory.read user/Slot.read" ```

**Comment by Torin-Shepard-athena** [comment]
For security purposes, it is important to have the ability to control which users can write to the system using APIs.

CPS 12.3 requires adding a record into the database for each user authorized to use Write scopes.  This allows CPS administrators to control which users can actually write to their system.

Substitute the desired value for the loginname placeholder in the following SQL statement.

insert into MedLists(TableName, FunctionName, Code, Description, Created, CreatedBy, LastModified, LastModifiedBy)
values('ClinicalWrites', 'Clinical Writes Allowed', (select PVID from DoctorFacility where LoginUser='loginname'), 'loginname', GETDATE(), 'System', GETDATE(), 'System')

The V20 release will have a new security permission so granting authorization to use API Clinical Writes can be done using CPS Administration module instead of adding a record into the database.

**Comment by KedarGanta** [comment]
Closing the issue. Please open another issue if you have more questions.
